### ISSUE TITLE
Add ability to read / parse Lib DOM definitions

### ISSUE THREAD

**Issue by IEvangelist** [IEvangelist/blazorators#1]
In the `TypeScript.TypeConverter` project, finish implementing the ability to read and parse the TypeScript definitions. The `LibDomParser` object is intended to cache a dictionary of all the types. The consuming library can call `InitializeAsync` to prepare it for usage. The `TryParseType` function is to be used by source generator. It will provide the type name, and the parser will attempt to return C# source text which is be added as source from the generator.

**Comment by WeihanLi** [comment]
How would the parsed C# source text look like? Is there a sample?

I tried with the current `InterfaceConverter` and the `AsCSharpSourceText` extension, if there's more than one interface, it would return an unexpected result, for example, I tried with the following typescript code to CSharp code

``` typescript
interface Person {
    Name: string;
    Age: number;
    Job: Job;
}
interface Job {
  Title: string;
}
```

Output C# code

``` c#
namespace Microsoft.JSInterop;

public record Person(
    string Name,
    number Age,
    Job Job,
    string Title
);
```

Would the extension method support multiple ts types?
