### ISSUE TITLE
This library does not appear to handle d.ts files besides LibDom

### ISSUE THREAD

**Issue by robertmclaws** [IEvangelist/blazorators#14]
It seems to me that if you can read LibDom, you can actually read any d.ts file.

By adding another property to the FileGeneratorAttribute, it seems like you could load any file from any location, parse it, and spit out a JSInvoke compatibility layer.

**Comment by IEvangelist** [comment]
Hi @robertmclaws,

You're absolutely correct. Right now, this is limited to the hardcoded `LibDomParser/Reader`. I will work on exposing the ability to add arbitrary TypeScript declaration support.

**Comment by IEvangelist** [comment]
> Thanks for getting back to me so quickly! How can I help make this happen within the next couple days? I need it for a project that goes to production late next week. You're the man!

Wow, that's a short deadline. I recently discovered a similar project, that already lets you arbitrarily point to TypeScript declarations. But it takes a different approach. It is worth exploring though:

https://github.com/canhorn/EventHorizon.Blazor.TypeScript.Interop.Generator

I would need to make several updates to expose the ability to control this value:

https://github.com/IEvangelist/blazorators/blob/main/src/Blazor.SourceGenerators/Readers/LibDomReader.cs#L17

This would probably be exposed through a new, optional property on the base `JSAutoInteropAttribute`. And when it is present, it would need to use a non-hardcoded version. This attribute is [mapped out](https://github.com/IEvangelist/blazorators/blob/main/src/Blazor.SourceGenerators/Extensions/AttributeSyntaxExtensions.cs#L10) into the [`GeneratorOptions` object](https://github.com/IEvangelist/blazorators/blob/main/src/Blazor.SourceGenerators/Options/GeneratorOptions.cs) when compiling. So, the option would need to be added and then used in the correct places. What do you think?

**Comment by robertmclaws** [comment]
I think that makes a lot of sense. I think the property should be an array of string, so you can add multiple files from the same generation run (if possible). I also think the `LibDomReader` needs to be renamed to `TypesFileReader`, and should know if the file path is local and needs a `File.Open`, or remote and need an `HttpClient`.

Thoughts?

**Comment by IEvangelist** [comment]
I love that. I do agree with most of the suggested changes.

- Yes, should be `File.Open` and `HttpClient` for local and remote.
- Yes, `LibDomReader` should be renamed, but I'd name it `TypeDeclarationReader`.
- Yes, it should be an array.

**Comment by IEvangelist** [comment]
Hi @robertmclaws - I addressed this in 972658f, I'll publish the NuGet bits soon. I think this is still a bit prescriptive. If you have a repo that you could share, I could have a look at it as well to help my understanding of what exactly you're trying to accomplish.

**Comment by kyrvlasiuk** [comment]
If someone comes by here and wonders why example for TypeDeclarationSources does not work - implementation was commented out, and only embedded lib.dom.d.ts is used
https://github.com/IEvangelist/blazorators/commit/9c720a283a1adb01df3d27e543f6a6cb3b56e6b9
