### ISSUE TITLE
Installing in an empty project breaks the build

### ISSUE THREAD

**Issue by robertmclaws** [IEvangelist/blazorators#15]
I installed the Blazor.SourceGenerators package into an existing .NET 6 Blazor WebAssembly project. When it drops [this attribute](https://github.com/IEvangelist/blazorators/blob/main/src/Blazor.SourceGenerators/Source/SourceCode.JSAutoInteropAttribute.cs) into the project, it breaks the build.

That code needs to drop whatever "using" statements need to be there for the code to work... and it should consider if it's possible to keep those assemblies in the Blazorators assembly if at all possible.

**Comment by robertmclaws** [comment]
I don't believe I referenced it as an analyzer, so that was probably the problem.

**Comment by IEvangelist** [comment]
Perfect, thank you.

**Comment by robertmclaws** [comment]
Actually it's not working at the moment. I tried what you said and that didn't work... those properties are for project references, not NuGet packages (you don't have to do that for Microsoft.CodeAnalysis.NetAnalyzers)

Tried using just a regular reference and getting this: 
![image](https://user-images.githubusercontent.com/1657085/162367515-084022ad-65ed-44d7-9cfa-bf974be029fb.png)

Notice that the SourceGenerator library is not showing up under Analyzers.

Interestingly, I get the sane red squigglies when pulling down this project and trying to compile, but the compile succeeds and doesn't throw any errors.

**Comment by IEvangelist** [comment]
Close and reopen Visual Studio. Unfortunately, that's been my experience too. Visual Studio does some weird caching of sorts I believe, and it causes issues. While it will compile, you won't get IntelliSense, and you'll see red squiggles. I should probably document this as something to be aware of for consumers.
