### ISSUE TITLE
SpeechRecognition fails on firefox and crashed blazor application

### ISSUE THREAD

**Issue by taori** [IEvangelist/blazorators#28]
Unhandled exception rendering component: webkitSpeechRecognition is not defined

**Comment by IEvangelist** [comment]
FireFox doesn't appear to support Speech Recognition at all. This is a limitation of that browser.

- https://caniuse.com/?search=speechrecognition

It might be a good idea to add this automated Can I Use URL to each API. Would that have been more helpful?

**Comment by taori** [comment]
I would check for undefined on webkitSpeechRecognition to begin with. Falling back to SpeechRecognition is fine, but the code is faulty and should crash in safari too, where SpeechRecognition is supported. One way  or another using the library should produce an error instead of a js crash

You attempted to fallback to SpeechRecognition in a way that i recall used to work (a || b) but that crashes now. So the implementation in js would have to be slightly changed to check both webkitSpeechRecognition and SpeechRecognition on undefined and report a not supported error, similar to Geolocation providing feedback that the user has canceled the dialog.

**Comment by IEvangelist** [comment]
Sounds good! Yes, I do think that we should report the error more accurately and not crash. Thanks for the feedback, and looking forward to reviewing a PR.

**Comment by IEvangelist** [comment]
@all-contributors please add @taori for bug

**Comment by taori** [comment]
How do i get the solution to build? I'm getting errors like this:

![grafik](https://user-images.githubusercontent.com/5545184/163450762-9b209813-4216-4bac-ba01-45d2480d1f5f.png)

**Comment by IEvangelist** [comment]
Hmmm, interesting. I have not witnessed errors like this before. What version of Visual Studio are you using? Are you doing a Debug build?

**Comment by IEvangelist** [comment]
Could you create a PR, and let the build system here see if it runs into the same error?

**Comment by taori** [comment]
https://github.com/taori/blazorators/actions/runs/2169057528

works in github actions, yes

**Comment by IEvangelist** [comment]
That's really weird! I'm not sure why that is happening, maybe you could remove the `MinVer` packages from the projects for local testing?

**Comment by taori** [comment]
Oddly enough i had to checkout again (fresh machine) and then debugging worked fine. Working on PR now.

**Comment by taori** [comment]
Do my changes look wrong to you? It's not hitting the breakpoint for the error method or displaying errors.

https://github.com/IEvangelist/blazorators/compare/main...taori:bugfix-speech-recognition-crash-fix?expand=1

**Comment by IEvangelist** [comment]
> Do my changes look wrong to you? It's not hitting the breakpoint(in blazor c# method, not js) for the error method or displaying errors.
> 
> https://github.com/IEvangelist/blazorators/compare/main...taori:bugfix-speech-recognition-crash-fix?expand=1

Did you test it in the demo app on FireFox? I don't think that will work, as the callback is expecting an `SpeechRecognitionErrorEvent` object, not two `string` parameters.

**Comment by taori** [comment]
I see. I guess i will look into how to add a "OnNotSupported" callback then? Or how would you handle it? Stopping without any information would not be good i think

**Comment by IEvangelist** [comment]
I think you had the right idea to use the `OnError` callback, just create an object manually.

`{ "error": "...", "message": "..."  }`
