### ISSUE TITLE
ILocalStorageService.RemoveItem doesn't remove item

### ISSUE THREAD

**Issue by SeanFeldman** [IEvangelist/blazorators#38]
Version: 2.0.11
Project: Blazor WebAssembly
.NET: 6

The call to `ILocalStorageService.RemoveItem(key)` doesn't remove the item from the local storage.

**Comment by IEvangelist** [comment]
Interesting, I'm seeing that too, but I know it was working before. Looking into what might be going on, thanks for reporting this.

**Comment by IEvangelist** [comment]
Can you clear your `localStorage` manually, and try to recreate this issue on this page?

- https://ievangelist.github.io/blazorators/todos

I'm not seeing the issue now.

**Comment by SeanFeldman** [comment]
Aha! That did the trick. Thank you. Not sure why removing the item didn't work. All is good now, thank you.

BTW, I noticed some weird key naming inconsistency with the Todos app 🙂 
![image](https://user-images.githubusercontent.com/1309622/211061350-d100107f-8bb5-44d4-ae61-21eb30b7f2aa.png)

**Comment by IEvangelist** [comment]
I rewrote how those are named now. That's fixed too.

**Comment by IEvangelist** [comment]
@all-contributors please add @SeanFeldman for bug
