### ISSUE TITLE
.NET 6.0 support

### ISSUE THREAD

**Issue by daver77** [IEvangelist/blazorators#41]
Hi, firstly thanks for the packages, I've been using LocalStorage and SessionStorage for a while now.

Most of our sites are on .NET 6.0 LTS running v2.0.11 of your packages. I've just noticed v7.0.x is now out but only supports .NET 7. Will you be continuing to updat 2.0.x with any fixes?

**Comment by IEvangelist** [comment]
Hi @daver77 - thanks for your kind words! Are you using WebAssembly or the Server-side bits?

II had intentions of supporting multitargeting, but hit a snag and stopped. I plan on adding that though, and for .NET 6 specifically, that is rather straightforward. Thanks for the idea!

@allcontributors please add @daver77 for ideas

**Comment by IEvangelist** [comment]
We multi-target now, supporting .NET 7.0 and .NET 8.0. closing this....
