### ISSUE TITLE
does not generate files ?

### ISSUE THREAD

**Issue by ignatandrei** [IEvangelist/blazorators#47]
For my list of https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG I want to give a simple example of using your generator ( yes, of course, I will add the other nuget packages)  . The simplest one is with
```csharp
[JSAutoGenericInterop(
    TypeName = "Storage",
    Implementation = "window.localStorage",
    Url = "https://developer.mozilla.org/docs/Web/API/Window/localStorage",
    GenericMethodDescriptors = new[]
    {
        "getItem",
        "setItem:value"
    })]

public interface ILocalStorageService
{
}
```

I put into csproj
```xml
<ItemGroup>
    <PackageReference Include="Blazor.Serialization" Version="8.0.0" />
    <PackageReference Include="Blazor.SourceGenerators" Version="8.0.0" OutputItemType="Analyzer">
    </PackageReference>
  </ItemGroup>
	
	<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GX</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>

```

But the files generated  into 
 BlazorApp1\BlazorApp1\obj\GX\Blazor.SourceGenerators\Blazor.SourceGenerators.JavaScriptInteropGenerator

are not containing any AddLocalStorageServices();

for builder.Services.AddLocalStorageServices();
Please tell me what I am doing wrong. 
Added the project to can reproduce the issue.
[BlazorApp1.zip](https://github.com/IEvangelist/blazorators/files/13848955/BlazorApp1.zip)

**Comment by IEvangelist** [comment]
Just now getting to this, sorry about that. Here's an example of how to consume the source generator:

https://github.com/IEvangelist/blazorators/blob/b41b4940b101288c61a4cc33bdf314be2b295f11/src/Blazor.LocalStorage/Blazor.LocalStorage.csproj#L64-L66

This is a `ProjectReference` but it should be the same for the `PackageReference`, perhaps try this:

```xml
<PackageReference Include="Blazor.SourceGenerators"
                  Version="8.0.0" 
                  OutputItemType="Analyzer"
                  SetTargetFramework="TargetFramework=netstandard2.0"
                  ReferenceOutputAssembly="false">
</PackageReference>
```

**Comment by ignatandrei** [comment]
I have put the package reference 
Still have error 

error CS1061: 'IServiceCollection' does not
 contain a definition for 'AddLocalStorageServices' and no accessible extension method 'AddLocalStorageServices' accept
ing a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly refe
rence?)

  The files generated on obj/GX are 

BlazorHostingModel.g.cs
JSAutoGenericInteropAttribute.g.cs
JSAutoInteropAttribute.g.cs
RecordCompat.g.cs

Attached the project . If you build, there are more files generated in obj/GX ?

[BlazorAppFullRef1.zip](https://github.com/IEvangelist/blazorators/files/13998283/BlazorAppFullRef1.zip)

**Comment by IEvangelist** [comment]
Oh I see, the interface needs to be `partial`. Change it to this:

```csharp
[JSAutoGenericInterop(
    TypeName = "Storage",
    Implementation = "window.localStorage",
    Url = "https://developer.mozilla.org/docs/Web/API/Window/localStorage",
    GenericMethodDescriptors = new[]
    {
        "getItem",
        "setItem:value"
    })]

public partial interface ILocalStorageService
{
}
```

**Comment by ignatandrei** [comment]
Now it works . 
Also, I have to add a globals.cs for
```csharp
global using Microsoft.JSInterop;
global using BlazorApp2; // this is the namespace where the interface resides
```

because the generating code is 
```csharp
internal readonly IJSInProcessRuntime;
```

**Comment by IEvangelist** [comment]
I guess our clue should have been to look at the existing package that generates based on this 🤣:

https://github.com/IEvangelist/blazorators/blob/b41b4940b101288c61a4cc33bdf314be2b295f11/src/Blazor.LocalStorage.WebAssembly/ILocalStorageService.cs#L4-L17

Can we close this now?

**Comment by ignatandrei** [comment]
Yes, I have what I need : https://ignatandrei.github.io/RSCG_Examples/v2/docs/Blazorators
