### ISSUE TITLE
Repeating the same words/phrases with new word

### ISSUE THREAD

**Issue by TheKhanSoft** [IEvangelist/blazorators#48]
Referring to **blazorators/listen**

It seems like the speech to text takes all the previous text, add new word to it and then add it to the previous text. For instance when I spoke **Have you been listening to me** I go the following results

`. . . . . Have. Have. Have you. Have you. Have you been. Have you been listening. Have you been listening to. Have you been listening to me.` 

That's the only sentence or phrase, but tried other sentences and phrases and got the same pattern.

**Comment by IEvangelist** [comment]
Interesting, it does accumulate and buffer previous with new. Perhaps I should have two streams? Have you tried the sample site:

- https://ievangelist.github.io/blazorators/listen

or is this a custom consumption of the NuGet package?

- https://www.nuget.org/packages/Blazor.SpeechRecognition.WebAssembly

Also, are you using WASM or server-side? I do have examples of both in source, please let me know if any of this solves your issue.

**Comment by TheKhanSoft** [comment]
Thank you for your prompt response.
I have been trying the demo in Chrome. 

![Screenshot_2024-01-27-12-31-53-682-edit_com android chrome](https://github.com/IEvangelist/blazorators/assets/4927267/6fb9ccd0-2616-4e20-8dd0-b30e68177d66)

**Comment by IEvangelist** [comment]
I just tested this out on my phones Chrome browser, and it worked. I'm at a loss.

![image](https://github.com/IEvangelist/blazorators/assets/7679720/46ac1e28-b9eb-4e0b-821e-664a604d85f3)

**Comment by IEvangelist** [comment]
There, I had to enable the mic - now it works in Chrome too: [![image](https://github.com/IEvangelist/blazorators/assets/7679720/5ebc8887-4df3-4f69-b5ae-83765587f38c)]()

**Comment by IEvangelist** [comment]
I'm at a loss here, @TheKhanSoft... I cannot recreate the issue. I'm going to close this, but if others experience it too, I'll try to investigate more.
