### ISSUE TITLE
Unable to create listen component in Blazor WebApp

### ISSUE THREAD

**Issue by uwefms** [IEvangelist/blazorators#51]
Hi everybody,

   thank you for your great work. I am enjoying it without any problems on Blazor Server projects. Now I tried to use it in a BlazorWebApp in @rendermode InteractiveAuto (or InteractiveAutoWebAssembly) in the client project. What I did:

Add Blazor.SpeechRecognition.WebAssembly 8.0.0 to the client csproj

Add builder.Services.AddSpeechRecognitionServices(); to program.cs in the client project

Used the code in ListenToMe provided in the Blazor.ExampleConsumer project

Projects compile without errors. When trying to call the ListenToMe via menu module, I get the following error:

InvalidOperationException: Cannot provide a value for property 'SpeechRecognition' on type 'SpeechWasm.Client.Pages.ListenToMe'. There is no registered service of type 'Microsoft.JSInterop.ISpeechRecognitionService'.

Is this a bug or am I doing something wrong ?

    regards

       Uwe

**Comment by IEvangelist** [comment]
You can't use the WebAssembly package for the interactive render modes. Try it again, but with the `Blazor.SpeechRecognition` package.

**Comment by uwefms** [comment]
Wow - that was fast ! Works like a charm ....

    Thank You
