### ISSUE TITLE
Speech Recognition fails on Blazor Server

### ISSUE THREAD

**Issue by EdCharbeneau** [IEvangelist/blazorators#60]
The service works fine on Web Assembly but not on Server. When I try to use Speech Recognition on Server, the code throws an error "aborted". This error is coming from the browser's API and I get no other information.

I am using the package Blazor.SpeechRecognition for the Server implementation.

**Comment by IEvangelist** [comment]
Hi @EdCharbeneau!

Luckily, I have a sample app written that verifies all this functionality. See the https://github.com/IEvangelist/blazorators/blob/main/samples/BlazorServer.ExampleConsumer/Pages/ListenToMe.razor.cs. You could clone the repo and just set this solution as the startup and verify it yourself - I just did locally.

I do know that there's lots of issues with server-side and `@rendermode`. Is it trying to do SSR, like is prerendering enabled? Similar to this issue: https://github.com/IEvangelist/blazorators/issues/59#issuecomment-2418329584

**Comment by EdCharbeneau** [comment]
I'll take a look, thanks 👍

**Comment by IEvangelist** [comment]
> I'll take a look, thanks 👍

Just let me know what you find out.

**Comment by IEvangelist** [comment]
> It appears that when you use cancel, that it may be normal for the "aborted" error to be triggered by the API. For some reason I'm only getting it on Blazor Server and not Client.
> 
> ```
> await SpeechRecognition.CancelSpeechRecognitionAsync(true) // error "aborted"
> ```
> 
> I also get an "error" when the service times out vs. being cancelled by the user.
> 
> ```
> "no-speech"
> ```
> 
> Here is what I ended up with
> 
> ```
>     public Task OnError(SpeechRecognitionErrorEvent args)
>     {
>         switch (args.Error)
>         {
>             case "audio-capture":
>             case "network":
>             case "not-allowed":
>             case "service-not-allowed":
>             case "bad-grammar":
>             case "language-not-supported":
>                 throw new Exception($"Speech: {args.Error}: {args.Message}");
>             case "no-speech":
>             case "aborted":
>                 break;
>         };
>         StateHasChanged();
>         return Task.CompletedTask;
>     }
> ```

Ah, you're passing in `true` for the `isAborted`... so that literally translates into the [`abort`](https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognition/abort) being called. Instead, pass `false` which will simply stop recognition.
